'use client';

import { useState } from 'react';
import { Project, AgencyInput } from '@/lib/types';

interface ExportButtonsProps {
  projects: Project[];
  input: AgencyInput;
}

export default function ExportButtons({ projects, input }: ExportButtonsProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    const content = generateTextExport(projects, input);
    navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExportText = () => {
    const content = generateTextExport(projects, input);
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'ai-projects-export.txt';
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleExportPDF = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const html = generatePDFHTML(projects, input);
    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.print();
  };

  return (
    <div className="flex flex-wrap gap-3">
      <button
        onClick={handleCopy}
        className="flex items-center gap-2 px-4 py-2 bg-white border border-gray-300 rounded-lg text-sm font-medium text-gray-700 hover:bg-gray-50 transition-colors"
      >
        {copied ? (
          <>
            <svg className="w-4 h-4 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
            </svg>
            Copied!
          </>
        ) : (
          <>
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
            </svg>
            Copy Plan
          </>
        )}
      </button>
      <button
        onClick={handleExportText}
        className="flex items-center gap-2 px-4 py-2 bg-white border border-gray-300 rounded-lg text-sm font-medium text-gray-700 hover:bg-gray-50 transition-colors"
      >
        <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
        </svg>
        Export TXT
      </button>
      <button
        onClick={handleExportPDF}
        className="flex items-center gap-2 px-4 py-2 bg-brand-purple text-white rounded-lg text-sm font-medium hover:opacity-90 transition-colors"
      >
        <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z" />
        </svg>
        Export PDF
      </button>
    </div>
  );
}

function generateTextExport(projects: Project[], input: AgencyInput): string {
  let content = `AI PROJECT ENGINE - Generated Projects\n`;
  content += `========================================\n\n`;
  
  content += `AGENCY DETAILS\n`;
  content += `--------------\n`;
  content += `Business Name: ${input.businessName || 'Not provided'}\n`;
  content += `Type: ${input.agencyType}\n`;
  content += `Client Niches: ${input.clientNiches}\n`;
  content += `Revenue: ${input.revenueRange}\n`;
  content += `Services: ${input.currentServices.join(', ')}\n`;
  content += `Pain Points: ${input.painPoints}\n`;
  content += `Goals: ${input.goals}\n\n`;
  
  content += `RECOMMENDED AI PROJECTS\n`;
  content += `----------------------\n\n`;
  
  projects.forEach((project, index) => {
    content += `${index + 1}. ${project.name}\n`;
    content += `   Category: ${project.category}\n`;
    content += `   Priority: #${project.priority}\n`;
    content += `   Score: ${project.scores.total.toFixed(1)}/10\n`;
    content += `   Description: ${project.description}\n`;
    content += `   Problem Solved: ${project.problem}\n\n`;
    content += `   Implementation:\n`;
    content += `   - Overview: ${project.implementation.overview}\n`;
    content += `   - Tools: ${project.implementation.tools.join(', ')}\n`;
    content += `   - Steps:\n`;
    project.implementation.steps.forEach((step, i) => {
      content += `     ${i + 1}. ${step}\n`;
    });
    content += `   - ROI: ${project.implementation.roiEstimate}\n\n`;
    content += `---\n\n`;
  });
  
  content += `Generated by AI Project Engine | HireZim AI\n`;
  content += `hirezim.ai\n`;
  
  return content;
}

function generatePDFHTML(projects: Project[], input: AgencyInput): string {
  const brandPurple = '#B02DD6';
  const brandBlack = '#111111';
  
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>AI Project Engine - ${input.businessName || 'Agency'} Plan</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;900&display=swap');
    
    * { margin: 0; padding: 0; box-sizing: border-box; }
    
    body {
      font-family: 'Inter', -apple-system, sans-serif;
      line-height: 1.6;
      color: #111111;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px;
    }
    
    .header {
      display: flex;
      align-items: center;
      justify-content: space-between;
      padding-bottom: 24px;
      border-bottom: 3px solid ${brandPurple};
      margin-bottom: 32px;
    }
    
    .logo {
      display: flex;
      align-items: center;
      gap: 8px;
    }
    
    .logo-img {
      height: 48px;
      width: auto;
    }
    
    .logo-text {
      font-weight: 700;
      font-size: 20px;
    }
    
    .brand-tagline {
      color: ${brandPurple};
      font-size: 12px;
      font-weight: 600;
    }
    
    .title-section {
      text-align: center;
      margin-bottom: 40px;
    }
    
    .title {
      font-size: 32px;
      font-weight: 900;
      color: ${brandBlack};
      margin-bottom: 8px;
    }
    
    .subtitle {
      font-size: 16px;
      color: #6B7280;
    }
    
    .agency-info {
      background: linear-gradient(135deg, ${brandPurple}10 0%, #F3E8F9 100%);
      border-radius: 12px;
      padding: 24px;
      margin-bottom: 32px;
      border-left: 4px solid ${brandPurple};
    }
    
    .agency-name {
      font-size: 24px;
      font-weight: 700;
      color: ${brandPurple};
      margin-bottom: 16px;
    }
    
    .info-grid {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 12px;
    }
    
    .info-item {
      font-size: 14px;
    }
    
    .info-label {
      font-weight: 600;
      color: #6B7280;
      font-size: 12px;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }
    
    .info-value {
      color: ${brandBlack};
    }
    
    .projects-section {
      margin-top: 32px;
    }
    
    .section-title {
      font-size: 20px;
      font-weight: 700;
      color: ${brandBlack};
      margin-bottom: 20px;
      padding-bottom: 8px;
      border-bottom: 2px solid #E5E7EB;
    }
    
    .project-card {
      background: white;
      border: 1px solid #E5E7EB;
      border-radius: 12px;
      padding: 20px;
      margin-bottom: 16px;
      page-break-inside: avoid;
    }
    
    .project-header {
      display: flex;
      align-items: flex-start;
      justify-content: space-between;
      margin-bottom: 12px;
    }
    
    .project-name {
      font-size: 18px;
      font-weight: 700;
      color: ${brandBlack};
    }
    
    .project-priority {
      background: ${brandPurple};
      color: white;
      padding: 4px 12px;
      border-radius: 20px;
      font-size: 12px;
      font-weight: 600;
    }
    
    .project-meta {
      display: flex;
      gap: 16px;
      margin-bottom: 12px;
      font-size: 13px;
      color: #6B7280;
    }
    
    .project-score {
      font-weight: 600;
      color: ${brandPurple};
    }
    
    .project-description {
      font-size: 14px;
      color: #374151;
      margin-bottom: 12px;
    }
    
    .project-section {
      margin-top: 12px;
    }
    
    .project-section-title {
      font-size: 13px;
      font-weight: 600;
      color: ${brandPurple};
      margin-bottom: 6px;
    }
    
    .project-section-content {
      font-size: 13px;
      color: #4B5563;
    }
    
    .tools-list {
      display: flex;
      flex-wrap: wrap;
      gap: 6px;
    }
    
    .tool-tag {
      background: #F3E8F9;
      color: ${brandPurple};
      padding: 2px 8px;
      border-radius: 4px;
      font-size: 12px;
      font-weight: 500;
    }
    
    .steps-list {
      list-style: none;
      padding-left: 0;
    }
    
    .steps-list li {
      font-size: 13px;
      padding: 4px 0;
      padding-left: 20px;
      position: relative;
    }
    
    .steps-list li::before {
      content: "→";
      position: absolute;
      left: 0;
      color: ${brandPurple};
    }
    
    .roi-box {
      background: linear-gradient(135deg, ${brandPurple}10 0%, #F0FDF4 100%);
      border: 1px solid ${brandPurple};
      border-radius: 8px;
      padding: 12px;
      margin-top: 12px;
      font-size: 13px;
    }
    
    .roi-label {
      font-weight: 600;
      color: ${brandPurple};
    }
    
    .footer {
      margin-top: 40px;
      padding-top: 24px;
      border-top: 2px solid #E5E7EB;
      text-align: center;
      font-size: 12px;
      color: #6B7280;
    }
    
    .footer-brand {
      font-weight: 700;
      color: ${brandPurple};
    }
    
    @media print {
      body { padding: 20px; }
      .project-card { break-inside: avoid; }
    }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">
      <img src="https://project-engine-production.up.railway.app/hirezim-logo.svg" alt="HireZim AI" class="logo-img" />
      <div>
        <div class="logo-text">AI Project Engine</div>
        <div class="brand-tagline">Powered by HireZim AI</div>
      </div>
    </div>
    <div style="text-align: right;">
      <div style="font-size: 12px; color: #6B7280;">Generated</div>
      <div style="font-size: 14px; font-weight: 600;">${new Date().toLocaleDateString()}</div>
    </div>
  </div>
  
  <div class="title-section">
    <div class="title">AI Project Engine</div>
    <div class="subtitle">Your Personalized AI Implementation Roadmap</div>
  </div>
  
  <div class="agency-info">
    <div class="agency-name">${input.businessName || 'Your Agency'}</div>
    <div class="info-grid">
      <div class="info-item">
        <div class="info-label">Agency Type</div>
        <div class="info-value">${input.agencyType}</div>
      </div>
      <div class="info-item">
        <div class="info-label">Client Niches</div>
        <div class="info-value">${input.clientNiches}</div>
      </div>
      <div class="info-item">
        <div class="info-label">Revenue Range</div>
        <div class="info-value">${input.revenueRange}</div>
      </div>
      <div class="info-item">
        <div class="info-label">Current Services</div>
        <div class="info-value">${input.currentServices.join(', ')}</div>
      </div>
    </div>
  </div>
  
  <div class="projects-section">
    <div class="section-title">Recommended AI Projects</div>
    
    ${projects.map((project, index) => `
    <div class="project-card">
      <div class="project-header">
        <div class="project-name">${index + 1}. ${project.name}</div>
        <div class="project-priority">Priority #${project.priority}</div>
      </div>
      <div class="project-meta">
        <span>Category: ${project.category}</span>
        <span class="project-score">Score: ${project.scores.total.toFixed(1)}/10</span>
      </div>
      <div class="project-description">
        <strong>Description:</strong> ${project.description}
      </div>
      <div class="project-description">
        <strong>Problem Solved:</strong> ${project.problem}
      </div>
      
      <div class="project-section">
        <div class="project-section-title">Tools Needed</div>
        <div class="tools-list">
          ${project.implementation.tools.map(tool => `<span class="tool-tag">${tool}</span>`).join('')}
        </div>
      </div>
      
      <div class="project-section">
        <div class="project-section-title">Implementation Steps</div>
        <ul class="steps-list">
          ${project.implementation.steps.map(step => `<li>${step}</li>`).join('')}
        </ul>
      </div>
      
      <div class="roi-box">
        <span class="roi-label">ROI Estimate:</span> ${project.implementation.roiEstimate}
      </div>
    </div>
    `).join('')}
  </div>
  
  <div class="footer">
    <p>Generated by <span class="footer-brand">AI Project Engine</span> from <span class="footer-brand">HireZim AI</span></p>
    <p>hirezim.ai | AI Automation Experts</p>
  </div>
</body>
</html>`;
}