'use client';

import { useState } from 'react';
import { Project, AgencyInput } from '@/lib/types';

interface ExportButtonsProps {
  projects: Project[];
  input: AgencyInput;
}

export default function ExportButtons({ projects, input }: ExportButtonsProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    const content = generateTextExport(projects, input);
    navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExport = () => {
    const content = generateTextExport(projects, input);
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'ai-projects-export.txt';
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex flex-wrap gap-3">
      <button
        onClick={handleCopy}
        className="flex items-center gap-2 px-4 py-2 bg-white border border-gray-300 rounded-lg text-sm font-medium text-gray-700 hover:bg-gray-50 transition-colors"
      >
        {copied ? (
          <>
            <svg className="w-4 h-4 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
            </svg>
            Copied!
          </>
        ) : (
          <>
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
            </svg>
            Copy Plan
          </>
        )}
      </button>
      <button
        onClick={handleExport}
        className="flex items-center gap-2 px-4 py-2 bg-white border border-gray-300 rounded-lg text-sm font-medium text-gray-700 hover:bg-gray-50 transition-colors"
      >
        <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
        </svg>
        Export Plan
      </button>
    </div>
  );
}

function generateTextExport(projects: Project[], input: AgencyInput): string {
  let content = `AI PROJECT ENGINE - Generated Projects\n`;
  content += `========================================\n\n`;
  
  content += `AGENCY DETAILS\n`;
  content += `--------------\n`;
  content += `Type: ${input.agencyType}\n`;
  content += `Client Niches: ${input.clientNiches}\n`;
  content += `Revenue: ${input.revenueRange}\n`;
  content += `Services: ${input.currentServices.join(', ')}\n`;
  content += `Pain Points: ${input.painPoints}\n`;
  content += `Goals: ${input.goals}\n\n`;
  
  content += `RECOMMENDED AI PROJECTS\n`;
  content += `----------------------\n\n`;
  
  projects.forEach((project, index) => {
    content += `${index + 1}. ${project.name}\n`;
    content += `   Category: ${project.category}\n`;
    content += `   Priority: #${project.priority}\n`;
    content += `   Score: ${project.scores.total.toFixed(1)}/10\n`;
    content += `   Description: ${project.description}\n`;
    content += `   Problem Solved: ${project.problem}\n\n`;
    content += `   Implementation:\n`;
    content += `   - Overview: ${project.implementation.overview}\n`;
    content += `   - Tools: ${project.implementation.tools.join(', ')}\n`;
    content += `   - Steps:\n`;
    project.implementation.steps.forEach((step, i) => {
      content += `     ${i + 1}. ${step}\n`;
    });
    content += `   - ROI: ${project.implementation.roiEstimate}\n\n`;
    content += `---\n\n`;
  });
  
  content += `Generated by AI Project Engine for Marketing Agencies\n`;
  
  return content;
}